import { library } from '@fortawesome/fontawesome-svg-core'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

// Import solid icons (most commonly used)
import {
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faChartLine,
  faChartBar,
  faTable,
  faDownload,
  faRefresh,
  faCog,
  faSearch,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faEye,
  faEyeSlash,
  faPlay,
  faPause,
  faStop,
  faPlus,
  faMinus,
  faTimes,
  faCheck,
  faExclamationTriangle,
  faInfoCircle,
  faBell,
  faUser,
  faHome,
  faClock,
  faCalendar,
  faPercent,
  faDollarSign,
  faCoins,
  faSignal,
  faServer,
  faDatabase,
  faCloud,
  faFile,
  faFolder,
  faEdit,
  faTrash,
  faCopy,
  faSave,
  faSpinner,
  faBars,
  faExpand,
  faCompress,
  faCalculator,
  faBullseye,
  faBalanceScale,
  faLightbulb,
  faShield,
  faRocket,
  faChevronUp,
  faChevronDown
} from '@fortawesome/free-solid-svg-icons'

// Import regular icons (selected few)
import {
  faHeart,
  faStar,
  faUser as faUserRegular,
  faClock as faClockRegular
} from '@fortawesome/free-regular-svg-icons'

// Prevent fontawesome from adding its CSS since we included it manually
config.autoAddCss = false

// Add icons to the library
library.add(
  // Solid icons
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faChartLine,
  faChartBar,
  faTable,
  faDownload,
  faRefresh,
  faCog,
  faSearch,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faEye,
  faEyeSlash,
  faPlay,
  faPause,
  faStop,
  faPlus,
  faMinus,
  faTimes,
  faCheck,
  faExclamationTriangle,
  faInfoCircle,
  faBell,
  faUser,
  faHome,
  faClock,
  faCalendar,
  faPercent,
  faDollarSign,
  faCoins,
  faSignal,
  faServer,
  faDatabase,
  faCloud,
  faFile,
  faFolder,
  faEdit,
  faTrash,
  faCopy,
  faSave,
  faSpinner,
  faBars,
  faExpand,
  faCompress,
  faCalculator,
  faBullseye,
  faBalanceScale,
  faLightbulb,
  faShield,
  faRocket,
  faChevronUp,
  faChevronDown,
  
  // Regular icons
  faHeart,
  faStar,
  faUserRegular,
  faClockRegular
)

export { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

// Export commonly used icons for direct use
export {
  faArrowUp as faTrendingUp,
  faArrowDown as faTrendingDown,
  faMinus,
  faArrowUp,
  faArrowDown,
  faChartLine,
  faChartBar,
  faTable,
  faClock,
  faSearch,
  faFilter,
  faRefresh,
  faDownload,
  faEye,
  faEyeSlash,
  faBars,
  faTimes,
  faExpand,
  faCompress,
  faSort,
  faSortUp,
  faSortDown,
  faCalculator,
  faBullseye,
  faBalanceScale,
  faLightbulb,
  faShield,
  faRocket,
  faExclamationTriangle,
  faChevronUp,
  faChevronDown,
  faPlay,
  faPause,
  faTrash
}
